language: node_js
node_js:
 - 14

branches:
  only:
    - main

addons:
  chrome: stable

before_script:
  - cd WEB_Q_A/client
  - npm install -g @angular/cli@latest


cache:
  directories:
    - node_modules

script:
  - ng build



# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN
#   keep-history: true
#   local-dir: ./dist/
#   on: