# .travis.yml at the repo root

language: generic
branches:
      only:
        - main
#os: windows

jobs:
  include:
  - name: front-end 
    language: node_js
    node_js:
    - 14
    addons:
      chrome: stable
    before_script:
      - cd WEB_Q_A/client
      - npm install -g @angular/cli@latest
      - npm ci
    cache:
      directories:
        - node_modules
    script:
      - ng build
  - name: back-end
    language: csharp
    mono: none
    dotnet: 5.0.402  
    before_script:
      - cd WEB_Q_A/API
    script:
      - dotnet restore
      - dotnet build

#script: if .travis/build.sh $TRAVIS_COMMIT_RANGE $TARGET; then echo "Building '$TARGET' ..." && cd $TARGET && scripts/ci.sh; else echo "No changes detected in '$TARGET'; skipping build."; fi