language: node_js
node_js:
 - 14

branches:
  only:
    - main

addons:
  chrome: stable

before_script:
  - cd client
  - yarn global add @angular/cli

cache:
  yarn: true
  directories:
    - node_modules

script:
  - ng lint
  - ng build --prod



deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
  on: